### ISSUE TITLE
add pinch and swipe for enlarge image

### ISSUE THREAD

**Issue by readygosports** [easemob/kefu-webim#62]
/**
- img view
  */
  easemobim.imgView = (function () {
  
  var imgViewWrap = document.createElement('div'),
      utils = easemobim.utils,
      img = document.createElement('img');
      imgContainerWrap = document.createElement('div');
  
  ```
  var elWidth, elHeight;
  
  // mode : 'pinch' or 'swipe'
  var mode = '';
  
  // distance between two touche points (mode : 'pinch')
  var distance = 0;
  var initialDistance = 0;
  
  // image scaling
  var scale = 1;
  var relativeScale = 1;
  var initialScale = 1;
  var maxScale = parseInt(2, 10);
  if (isNaN(maxScale) || maxScale <= 1) {
      maxScale = 3;
  }
  
  // position of the upper left corner of the element
  var positionX = 0;
  var positionY = 0;
  
  var initialPositionX = 0;
  var initialPositionY = 0;
  
  // central origin (mode : 'pinch')
  var originX = 0;
  var originY = 0;
  
  // start coordinate and amount of movement (mode : 'swipe')
  var startX = 0;
  var startY = 0;
  var moveX = 0;
  var moveY = 0;
  ```
  
  img.style.cssText = '\
  position: absolute;\
    width:80%;\
  top: 0;\
  left: 0;\
  right: 0;\
  bottom: 0;\
  margin: auto;';
  imgViewWrap.appendChild(img);
  
  imgViewWrap.style.cssText = '\
  display: none;\
  z-index: 100000;\
  position: fixed;\
  width: 100%;\
  height: 100%;\
  left: 0;\
  top: 0;\
  background: rgba(0,0,0,.5);';
  document.body.appendChild(imgViewWrap);
  
  var reset = function () {
      imgViewWrap.style.display = 'none';
      imgViewWrap.style.overflow = 'hidden';
  };
  
  img.onload = function () {
            element=img;
  
  ```
          elWidth = img.clientWidth;
          elHeight = img.clientHeight;
          img.style.transformOrigin='50% 50%'
          img.style.webkitTransformationOrigin='50% 50%'
  
          var matrixArray = [1, 0, 0, 1, 0, 0];
          var matrix      = 'matrix(' + matrixArray.join(',') + ')';
          element.style.transform=matrix;
          element.style.webkitTransform=matrix + ' translate3d(0,0,0)';
  
  
          img.addEventListener('touchstart', touchstartHandler);
          img.addEventListener('touchmove', touchmoveHandler);
          img.addEventListener('touchend', touchendHandler);
  if ( this.width > easemobim.utils.window.width * .9 || this.height > easemobim.utils.window.height * .9 ) {
  
  } else {
      reset();
  }
  ```
  
  };
  
  ```
  function touchstartHandler(evt) {
  var touches = evt.originalEvent ? evt.originalEvent.touches : evt.touches;
  
  startX = touches[0].clientX;
  startY = touches[0].clientY;
  initialPositionX = positionX;
  initialPositionY = positionY;
  moveX = 0;
  moveY = 0;
  ```
  
    }
  
    /**
  - @param {object} evt
    */
    function touchmoveHandler(evt) {
      var touches = evt.originalEvent ? evt.originalEvent.touches : evt.touches;
    
      if (mode === '') {
        if (touches.length === 1 && scale > 1) {
    
    ```
      mode = 'swipe';
    
    } else if (touches.length === 2) {
    
      mode = 'pinch';
    
      initialScale = scale;
      initialDistance = getDistance(touches);
      originX = touches[0].clientX -
                parseInt((touches[0].clientX - touches[1].clientX) / 2, 10) -
                element[0].offsetLeft - initialPositionX;
      originY = touches[0].clientY -
                parseInt((touches[0].clientY - touches[1].clientY) / 2, 10) -
                element[0].offsetTop - initialPositionY;
    
    }
    ```
    
      }
    
      if (mode === 'swipe') {
        evt.preventDefault();
    
    ```
    moveX = touches[0].clientX - startX;
    moveY = touches[0].clientY - startY;
    
    positionX = initialPositionX + moveX;
    positionY = initialPositionY + moveY;
    
    transformElement();
    ```
    
      } else if (mode === 'pinch') {
        evt.preventDefault();
    
    ```
    distance = getDistance(touches);
    relativeScale = distance / initialDistance;
    scale = relativeScale * initialScale;
    
    positionX = originX * (1 - relativeScale) + initialPositionX + moveX;
    positionY = originY * (1 - relativeScale) + initialPositionY + moveY;
    
    transformElement();
    ```
    
      }
    }
    
    /**
  - @param {object} evt
    */
    function touchendHandler(evt) {
      var touches = evt.originalEvent ? evt.originalEvent.touches : evt.touches;
    
      if (mode === '' || touches.length > 0) {
        return;
      }
    
      if (scale < 1) {
    
    ```
    scale = 1;
    positionX = 0;
    positionY = 0;
    ```
    
      } else if (scale > maxScale) {
    
    ```
    scale = maxScale;
    relativeScale = scale / initialScale;
    positionX = originX * (1 - relativeScale) + initialPositionX + moveX;
    positionY = originY * (1 - relativeScale) + initialPositionY + moveY;
    ```
    
      } else {
    
    ```
    // if (positionX > 0) {
    //   positionX = 0;
    // } else if (positionX < elWidth * (1 - scale)) {
    //   positionX = elWidth * (1 - scale);
    // }
    // if (positionY > 0) {
    //   positionY = 0;
    // } else if (positionY < elHeight * (1 - scale)) {
    //   positionY = elHeight * (1 - scale);
    // }
    ```
    
      }
    
      transformElement();
      mode = '';
    }
    
    /**
  - @param {Array} touches
  - @return {number}
    */
    function getDistance(touches) {
      var d = Math.sqrt(Math.pow(touches[0].clientX - touches[1].clientX, 2) +
                        Math.pow(touches[0].clientY - touches[1].clientY, 2));
      return parseInt(d, 10);
    }
    
    /**
  - @param {number} [duration]
    */
    function transformElement(duration) {
      var transition  = duration ? 'all cubic-bezier(0,0,.5,1) ' + duration + 's' : '';
      var matrixArray = [scale, 0, 0, scale, positionX, positionY];
      var matrix      = 'matrix(' + matrixArray.join(',') + ')';
    
      element.style.transition=transition;
      element.style.webkittransition=transition;
      element.style.transform=matrix;
      element.style.webkitTransform=matrix + ' translate3d(0,0,0)';
    
      // element.css({
      //   '-webkit-transition' : transition,
      //   transition           : transition,
      //   '-webkit-transform'  : matrix + ' translate3d(0,0,0)',
      //   transform            : matrix
      // });
    }
  
  utils.on(imgViewWrap, 'click', reset, false);
      utils.on(imgViewWrap, 'ontouchstart', reset, false);
  
  return {
      show: function ( url ) {
          img.setAttribute('src', url);
          imgViewWrap.style.display = 'block';
          imgViewWrap.style.overflow = 'auto';
      }
  };
  }());

**Comment by index-swf** [comment]
以后会考虑加入此功能，感谢贡献代码

**Comment by index-swf** [comment]
以后会增加图片下载按钮，让用户下载到本地查看
